///@description Load Game

function scr_LoadGame(argument0)
{
	ini_open(argument0);
	global.pointStars = ini_read_real("stats","pointStars",0);
	global.points = ini_read_real("stats","points",0);
	global.playerLives = ini_read_real("stats","lives",3);
	global.goldenTomato = ini_read_real("stats","goldenTomato",false);
	
	global.shopGearCubeFirstTime = ini_read_real("shop","shopGearCubeFirstTime",true);
	global.shopGearCubeNewItem = ini_read_real("shop","shopGearCubeNewItem",false);
	
	global.extraModeUnlocked = ini_read_real("unlocks","extraModeUnlocked",false);
	global.maykrUnlocked = ini_read_real("unlocks","maykrUnlocked",true);
	global.skylandsUnlocked = ini_read_real("unlocks","skylandsUnlocked",false);
	global.gamblionUnlocked = ini_read_real("unlocks","gamblionUnlocked",false);
	global.bitcrushedUnlocked = ini_read_real("unlocks","bitcrushedUnlocked",false);
	global.samuraiKirbyUnlocked = ini_read_real("unlocks","samuraiKirbyUnlocked",false);
	
	global.kirbyUnlocked = ini_read_real("unlocks","kirbyUnlocked",true);
	global.gambleUnlocked = ini_read_real("unlocks","gambleUnlocked",false);
	global.metaKnightUnlocked = ini_read_real("unlocks","metaKnightUnlocked",false);
	global.keebyUnlocked = ini_read_real("unlocks","keebyUnlocked",false);
	global.princeFluffUnlocked = ini_read_real("unlocks","princeFluffUnlocked",false);
	
	global.friendlyPinkSprayPaintUnlocked = ini_read_real("unlocks","friendlyPinkSprayPaintUnlocked",true);
	global.yellowSprayPaintUnlocked = ini_read_real("unlocks","yellowSprayPaintUnlocked",true);
	global.redSprayPaintUnlocked = ini_read_real("unlocks","redSprayPaintUnlocked",true);
	global.greenSprayPaintUnlocked = ini_read_real("unlocks","greenSprayPaintUnlocked",true);
	global.dreamyBlueberrySprayPaintUnlocked = ini_read_real("unlocks","dreamyBlueberrySprayPaintUnlocked",true);
	global.waddleWaddleSprayPaintUnlocked = ini_read_real("unlocks","waddleWaddleSprayPaintUnlocked",true);
	global.mysticSprayPaintUnlocked = ini_read_real("unlocks","mysticSprayPaintUnlocked",true);
	global.shadowOfTheMirrorSprayPaintUnlocked = ini_read_real("unlocks","shadowOfTheMirrorSprayPaintUnlocked",true);
	global.greenjoltSprayPaintUnlocked = ini_read_real("unlocks","greenjoltSprayPaintUnlocked",true);
	global.butterKnifeSprayPaintUnlocked = ini_read_real("unlocks","butterKnifeSprayPaintUnlocked",true);
	global.blurpleSprayPaintUnlocked = ini_read_real("unlocks","blurpleSprayPaintUnlocked",true);
	global.beamSprayPaintUnlocked = ini_read_real("unlocks","beamSprayPaintUnlocked",true);
	global.stoneSprayPaintUnlocked = ini_read_real("unlocks","stoneSprayPaintUnlocked",true);
	global.mirrorSprayPaintUnlocked = ini_read_real("unlocks","mirrorSprayPaintUnlocked",true);
	global.fireSprayPaintUnlocked = ini_read_real("unlocks","fireSprayPaintUnlocked",true);
	global.iceSprayPaintUnlocked = ini_read_real("unlocks","iceSprayPaintUnlocked",true);
	global.plasmaSprayPaintUnlocked = ini_read_real("unlocks","plasmaSprayPaintUnlocked",true);
	global.unearthlyHandSprayPaintUnlocked = ini_read_real("unlocks","unearthlyHandSprayPaintUnlocked",true);
	global.soMetaSprayPaintUnlocked = ini_read_real("unlocks","soMetaSprayPaintUnlocked",true);
	global.telltaleKeebySprayPaintUnlocked = ini_read_real("unlocks","telltaleKeebySprayPaintUnlocked",true);
	global.royalYarnSprayPaintUnlocked = ini_read_real("unlocks","royalYarnSprayPaintUnlocked",true);
	global.smileyWhiteSprayPaintUnlocked = ini_read_real("unlocks","smileyWhiteSprayPaintUnlocked",true);
	global.eddSprayPaintUnlocked = ini_read_real("unlocks","eddSprayPaintUnlocked",true);
	
	global.gambleFamiliarUnlocked = ini_read_real("unlocks","gambleFamiliarUnlocked",true);
	global.gambleFamiliarLevel = ini_read_real("unlocks","gambleFamiliarLevel",1);
	global.gambleFamiliarExp = ini_read_real("unlocks","gambleFamiliarExp",0);
	global.happyPeaFamiliarUnlocked = ini_read_real("unlocks","happyPeaFamiliarUnlocked",true);
	global.happyPeaFamiliarLevel = ini_read_real("unlocks","happyPeaFamiliarLevel",1);
	global.happyPeaFamiliarExp = ini_read_real("unlocks","happyPeaFamiliarExp",0);
	global.epicJarFamiliarUnlocked = ini_read_real("unlocks","epicJarFamiliarUnlocked",true);
	global.epicJarFamiliarLevel = ini_read_real("unlocks","epicJarFamiliarLevel",1);
	global.epicJarFamiliarExp = ini_read_real("unlocks","epicJarFamiliarExp",0);
	global.krackleFamiliarUnlocked = ini_read_real("unlocks","krackleFamiliarUnlocked",true);
	global.krackleFamiliarLevel = ini_read_real("unlocks","krackleFamiliarLevel",1);
	global.krackleFamiliarExp = ini_read_real("unlocks","krackleFamiliarExp",0);
	
	global.beamGoldenFlareUpgradeUnlocked = ini_read_real("unlocks","beamGoldenFlareUpgradeUnlocked",true);
	global.mysticBeamVortexInAJarUpgradeUnlocked = ini_read_real("unlocks","mysticBeamVortexInAJarUpgradeUnlocked",true);
	global.stoneRockCandyUpgradeUnlocked = ini_read_real("unlocks","stoneRockCandyUpgradeUnlocked",true);
	global.stoneComboCobaltUpgradeUnlocked = ini_read_real("unlocks","stoneComboCobaltUpgradeUnlocked",true);
	global.bombMultiBombUpgradeUnlocked = ini_read_real("unlocks","bombMultiBombUpgradeUnlocked",true);
	global.bombEyeBombUpgradeUnlocked = ini_read_real("unlocks","bombEyeBombUpgradeUnlocked",true);
	global.bombSmartBombUpgradeUnlocked = ini_read_real("unlocks","bombSmartBombUpgradeUnlocked",true);
	global.bombMagmaBombUpgradeUnlocked = ini_read_real("unlocks","bombMagmaBombUpgradeUnlocked",true);
	global.bombExplosivePowderUpgradeUnlocked = ini_read_real("unlocks","bombExplosivePowderUpgradeUnlocked",true);
	global.fireMagicCharcoalUpgradeUnlocked = ini_read_real("unlocks","fireMagicCharcoalUpgradeUnlocked",true);
	global.iceEmptyConeUpgradeUnlocked = ini_read_real("unlocks","iceEmptyConeUpgradeUnlocked",true);
	global.sparkBrightPluggUpgradeUnlocked = ini_read_real("unlocks","sparkBrightPluggUpgradeUnlocked",true);
	global.waterEggSoilUpgradeUnlocked = ini_read_real("unlocks","waterEggSoilUpgradeUnlocked",true);
	
	var sprayPaintKirbyP1 = ini_read_string("playerCustomization","sprayPaintKirbyP1","spr_Kirby_Normal_Palette_FriendlyPink");
	global.sprayPaintKirbyP1 = asset_get_index(sprayPaintKirbyP1);
	var sprayPaintKirbyP2 = ini_read_string("playerCustomization","sprayPaintKirbyP2","spr_Kirby_Normal_Palette_Yellow");
	global.sprayPaintKirbyP2 = asset_get_index(sprayPaintKirbyP2);
	
	global.characterP1 = ini_read_string("playerCustomization","characterP1","kirby");
	global.characterP2 = ini_read_string("playerCustomization","characterP2","kirby");
	global.isHelperP1 = ini_read_real("playerCustomization","isHelperP1",false);
	global.isHelperP2 = ini_read_real("playerCustomization","isHelperP2",false);
	global.familiarP1 = ini_read_string("playerCustomization","familiarP1",false);
	global.familiarP2 = ini_read_string("playerCustomization","familiarP2",false);
	
	global.hatTypeCutterP1 = ini_read_string("playerCustomization","hatTypeCutterP1","kssu");
	global.hatTypeBeamP1 = ini_read_string("playerCustomization","hatTypeBeamP1","kssu");
	global.hatTypeStoneP1 = ini_read_string("playerCustomization","hatTypeStoneP1","kssu");
	global.hatTypeUfoP1 = ini_read_string("playerCustomization","hatTypeUfoP1","modern");
	global.hatTypeMirrorP1 = ini_read_string("playerCustomization","hatTypeMirrorP1","kssu");
	global.hatTypeNinjaP1 = ini_read_string("playerCustomization","hatTypeNinjaP1","kssu");
	global.hatTypeBombP1 = ini_read_string("playerCustomization","hatTypeBombP1","kssu");
	global.hatTypeFireP1 = ini_read_string("playerCustomization","hatTypeFireP1","kssu");
	global.hatTypeIceP1 = ini_read_string("playerCustomization","hatTypeIceP1","kssu");
	global.hatTypeSparkP1 = ini_read_string("playerCustomization","hatTypeSparkP1","kssu");
	global.hatTypeYoyoP1 = ini_read_string("playerCustomization","hatTypeYoyoP1","kssu");
	global.hatTypeWheelP1 = ini_read_string("playerCustomization","hatTypeWheelP1","kssu");
	global.hatTypeArtistP1 = ini_read_string("playerCustomization","hatTypeArtistP1","modern");
	global.hatTypeFighterP1 = ini_read_string("playerCustomization","hatTypeFighterP1","kssu");
	global.hatTypeSuplexP1 = ini_read_string("playerCustomization","hatTypeSuplexP1","kssu");
	global.hatTypeWingP1 = ini_read_string("playerCustomization","hatTypeWingP1","kssu");
	global.hatTypeJetP1 = ini_read_string("playerCustomization","hatTypeJetP1","kssu");
	global.hatTypeSwordP1 = ini_read_string("playerCustomization","hatTypeSwordP1","kssu");
	global.hatTypeParasolP1 = ini_read_string("playerCustomization","hatTypeParasolP1","kssu");
	global.hatTypeHammerP1 = ini_read_string("playerCustomization","hatTypeHammerP1","kssu");
	global.hatTypeBellP1 = ini_read_string("playerCustomization","hatTypeBellP1","modern");
	global.hatTypeSleepP1 = ini_read_string("playerCustomization","hatTypeSleepP1","kssu");
	global.hatTypeScanP1 = ini_read_string("playerCustomization","hatTypeScanP1","kssu");
	
	global.hatTypeCutterP2 = ini_read_string("playerCustomization","hatTypeCutterP2","kssu");
	global.hatTypeBeamP2 = ini_read_string("playerCustomization","hatTypeBeamP2","kssu");
	global.hatTypeStoneP2 = ini_read_string("playerCustomization","hatTypeStoneP2","kssu");
	global.hatTypeUfoP2 = ini_read_string("playerCustomization","hatTypeUfoP2","modern");
	global.hatTypeMirrorP2 = ini_read_string("playerCustomization","hatTypeMirrorP2","modern");
	global.hatTypeNinjaP2 = ini_read_string("playerCustomization","hatTypeNinjaP2","kssu");
	global.hatTypeBombP2 = ini_read_string("playerCustomization","hatTypeBombP2","kssu");
	global.hatTypeFireP2 = ini_read_string("playerCustomization","hatTypeFireP2","kssu");
	global.hatTypeIceP2 = ini_read_string("playerCustomization","hatTypeIceP2","kssu");
	global.hatTypeSparkP2 = ini_read_string("playerCustomization","hatTypeSparkP2","kssu");
	global.hatTypeYoyoP2 = ini_read_string("playerCustomization","hatTypeYoyoP2","kssu");
	global.hatTypeWheelP2 = ini_read_string("playerCustomization","hatTypeWheelP2","kssu");
	global.hatTypeArtistP2 = ini_read_string("playerCustomization","hatTypeArtistP2","kssu");
	global.hatTypeFighterP2 = ini_read_string("playerCustomization","hatTypeFighterP2","kssu");
	global.hatTypeSuplexP2 = ini_read_string("playerCustomization","hatTypeSuplexP2","kssu");
	global.hatTypeWingP2 = ini_read_string("playerCustomization","hatTypeWingP2","kssu");
	global.hatTypeJetP2 = ini_read_string("playerCustomization","hatTypeJetP2","kssu");
	global.hatTypeSwordP2 = ini_read_string("playerCustomization","hatTypeSwordP2","kssu");
	global.hatTypeParasolP2 = ini_read_string("playerCustomization","hatTypeParasolP2","kssu");
	global.hatTypeHammerP2 = ini_read_string("playerCustomization","hatTypeHammerP2","kssu");
	global.hatTypeBellP2 = ini_read_string("playerCustomization","hatTypeBellP2","modern");
	global.hatTypeSleepP2 = ini_read_string("playerCustomization","hatTypeSleepP2","kssu");
	global.hatTypeScanP2 = ini_read_string("playerCustomization","hatTypeScanP2","kssu");
	
	global.hatPaletteCutterKssuP1 = ini_read_real("playerCustomization","hatPaletteCutterKssuP1",0);
	global.hatPaletteBeamKssuP1 = ini_read_real("playerCustomization","hatPaletteBeamKssuP1",0);
	global.hatPaletteBeamMarxSoulP1 = ini_read_real("playerCustomization","hatPaletteBeamMarxSoulP1",0);
	global.hatPaletteStoneKssuP1 = ini_read_real("playerCustomization","hatPaletteStoneKssuP1",0);
	global.hatPaletteStoneModernP1 = ini_read_real("playerCustomization","hatPaletteStoneModernP1",0);
	global.hatPaletteUfoKssuP1 = ini_read_real("playerCustomization","hatPaletteUfoKssuP1",0);
	global.hatPaletteMirrorKssuP1 = ini_read_real("playerCustomization","hatPaletteMirrorKssuP1",0);
	global.hatPaletteMirrorModernP1 = ini_read_real("playerCustomization","hatPaletteMirrorModernP1",0);
	global.hatPaletteNinjaKssuP1 = ini_read_real("playerCustomization","hatPaletteNinjaKssuP1",0);
	global.hatPaletteNinjaModernP1 = ini_read_real("playerCustomization","hatPaletteNinjaModernP1",0);
	global.hatPaletteBombKssuP1 = ini_read_real("playerCustomization","hatPaletteBombKssuP1",0);
	global.hatPaletteBombModernP1 = ini_read_real("playerCustomization","hatPaletteBombModernP1",0);
	global.hatPaletteFireKssuP1 = ini_read_real("playerCustomization","hatPaletteFireKssuP1",0);
	global.hatPaletteIceKssuP1 = ini_read_real("playerCustomization","hatPaletteIceKssuP1",0);
	global.hatPaletteIceSnowmanP1 = ini_read_real("playerCustomization","hatPaletteIceSnowmanP1",0);
	global.hatPaletteSparkKssuP1 = ini_read_real("playerCustomization","hatPaletteSparkKssuP1",0);
	global.hatPaletteYoyoKssuP1 = ini_read_real("playerCustomization","hatPaletteYoyoKssuP1",0);
	global.hatPaletteWheelKssuP1 = ini_read_real("playerCustomization","hatPaletteWheelKssuP1",0);
	global.hatPaletteArtistKssuP1 = ini_read_real("playerCustomization","hatPaletteArtistKssuP1",0);
	global.hatPaletteArtistModernP1 = ini_read_real("playerCustomization","hatPaletteArtistModernP1",0);
	global.hatPaletteFighterKssuP1 = ini_read_real("playerCustomization","hatPaletteFighterKssuP1",0);
	global.hatPaletteSuplexKssuP1 = ini_read_real("playerCustomization","hatPaletteSuplexKssuP1",0);
	global.hatPaletteWingKssuP1 = ini_read_real("playerCustomization","hatPaletteWingKssuP1",0);
	global.hatPaletteJetKssuP1 = ini_read_real("playerCustomization","hatPaletteJetKssuP1",0);
	global.hatPaletteSwordKssuP1 = ini_read_real("playerCustomization","hatPaletteSwordKssuP1",0);
	global.hatPaletteParasolKssuP1 = ini_read_real("playerCustomization","hatPaletteParasolKssuP1",0);
	global.hatPaletteHammerKssuP1 = ini_read_real("playerCustomization","hatPaletteHammerKssuP1",0);
	global.hatPaletteBellModernP1 = ini_read_real("playerCustomization","hatPaletteBellModernP1",0);
	global.hatPaletteSleepKssuP1 = ini_read_real("playerCustomization","hatPaletteSleepKssuP1",0);
	global.hatPaletteScanKssuP1 = ini_read_real("playerCustomization","hatPaletteScanKssuP1",0);
	
	global.hatPaletteCutterKssuP2 = ini_read_real("playerCustomization","hatPaletteCutterKssuP2",0);
	global.hatPaletteBeamKssuP2 = ini_read_real("playerCustomization","hatPaletteBeamKssuP2",0);
	global.hatPaletteBeamMarxSoulP2 = ini_read_real("playerCustomization","hatPaletteBeamMarxSoulP2",0);
	global.hatPaletteStoneKssuP2 = ini_read_real("playerCustomization","hatPaletteStoneKssuP2",0);
	global.hatPaletteStoneModernP2 = ini_read_real("playerCustomization","hatPaletteStoneModernP2",0);
	global.hatPaletteUfoKssuP2 = ini_read_real("playerCustomization","hatPaletteUfoKssuP2",0);
	global.hatPaletteMirrorKssuP2 = ini_read_real("playerCustomization","hatPaletteMirrorKssuP2",0);
	global.hatPaletteMirrorModernP2 = ini_read_real("playerCustomization","hatPaletteMirrorModernP2",0);
	global.hatPaletteNinjaKssuP2 = ini_read_real("playerCustomization","hatPaletteNinjaKssuP2",0);
	global.hatPaletteNinjaModernP2 = ini_read_real("playerCustomization","hatPaletteNinjaModernP2",0);
	global.hatPaletteBombKssuP2 = ini_read_real("playerCustomization","hatPaletteBombKssuP2",0);
	global.hatPaletteBombModernP2 = ini_read_real("playerCustomization","hatPaletteBombModernP2",0);
	global.hatPaletteFireKssuP2 = ini_read_real("playerCustomization","hatPaletteFireKssuP2",0);
	global.hatPaletteIceKssuP2 = ini_read_real("playerCustomization","hatPaletteIceKssuP2",0);
	global.hatPaletteIceSnowmanP2 = ini_read_real("playerCustomization","hatPaletteIceSnowmanP2",0);
	global.hatPaletteSparkKssuP2 = ini_read_real("playerCustomization","hatPaletteSparkKssuP2",0);
	global.hatPaletteYoyoKssuP2 = ini_read_real("playerCustomization","hatPaletteYoyoKssuP2",0);
	global.hatPaletteWheelKssuP2 = ini_read_real("playerCustomization","hatPaletteWheelKssuP2",0);
	global.hatPaletteArtistKssuP2 = ini_read_real("playerCustomization","hatPaletteArtistKssuP2",0);
	global.hatPaletteArtistModernP2 = ini_read_real("playerCustomization","hatPaletteArtistModernP2",0);
	global.hatPaletteFighterKssuP2 = ini_read_real("playerCustomization","hatPaletteFighterKssuP2",0);
	global.hatPaletteSuplexKssuP2 = ini_read_real("playerCustomization","hatPaletteSuplexKssuP2",0);
	global.hatPaletteWingKssuP2 = ini_read_real("playerCustomization","hatPaletteWingKssuP2",0);
	global.hatPaletteJetKssuP2 = ini_read_real("playerCustomization","hatPaletteJetKssuP2",0);
	global.hatPaletteSwordKssuP2 = ini_read_real("playerCustomization","hatPaletteSwordKssuP2",0);
	global.hatPaletteParasolKssuP2 = ini_read_real("playerCustomization","hatPaletteParasolKssuP2",0);
	global.hatPaletteHammerKssuP2 = ini_read_real("playerCustomization","hatPaletteHammerKssuP2",0);
	global.hatPaletteBellModernP2 = ini_read_real("playerCustomization","hatPaletteBellModernP2",0);
	global.hatPaletteSleepKssuP2 = ini_read_real("playerCustomization","hatPaletteSleepKssuP2",0);
	global.hatPaletteScanKssuP2 = ini_read_real("playerCustomization","hatPaletteScanKssuP2",0);
	
	global.beamGoldenFlareUpgradeEquipped = ini_read_real("playerCustomization","beamGoldenFlareUpgradeEquipped",false);
	global.mysticBeamVortexInAJarUpgradeEquipped = ini_read_real("playerCustomization","mysticBeamVortexInAJarUpgradeEquipped",false);
	global.stoneRockCandyUpgradeEquipped = ini_read_real("playerCustomization","stoneRockCandyUpgradeEquipped",false);
	global.stoneComboCobaltUpgradeEquipped = ini_read_real("playerCustomization","stoneComboCobaltUpgradeEquipped",false);
	global.bombMultiBombUpgradeEquipped = ini_read_real("playerCustomization","bombMultiBombUpgradeEquipped",false);
	global.bombEyeBombUpgradeEquipped = ini_read_real("playerCustomization","bombEyeBombUpgradeEquipped",false);
	global.bombSmartBombUpgradeEquipped = ini_read_real("playerCustomization","bombSmartBombUpgradeEquipped",false);
	global.bombMagmaBombUpgradeEquipped = ini_read_real("playerCustomization","bombMagmaBombUpgradeEquipped",false);
	global.bombExplosivePowderUpgradeEquipped = ini_read_real("playerCustomization","bombExplosivePowderUpgradeEquipped",false);
	global.fireMagicCharcoalUpgradeEquipped = ini_read_real("playerCustomization","fireMagicCharcoalUpgradeEquipped",false);
	global.iceEmptyConeUpgradeEquipped = ini_read_real("playerCustomization","iceEmptyConeUpgradeEquipped",false);
	global.sparkBrightPluggUpgradeEquipped = ini_read_real("playerCustomization","sparkBrightPluggUpgradeEquipped",false);
	global.waterEggSoilUpgradeEquipped = ini_read_real("playerCustomization","waterEggSoilUpgradeEquipped",false);
	
	ini_close();
}